# Cevap 1

In [1]:
#1'den 200'ye kadar olan çift sayılardan oluşan 10 X 10'luk bir dizi oluşturun. 
#arange() fonksiyonu yardımcı olabilir.
import numpy as np
a=np.arange(0,200,2).reshape(10,10)
print(a)


[[  0   2   4   6   8  10  12  14  16  18]
 [ 20  22  24  26  28  30  32  34  36  38]
 [ 40  42  44  46  48  50  52  54  56  58]
 [ 60  62  64  66  68  70  72  74  76  78]
 [ 80  82  84  86  88  90  92  94  96  98]
 [100 102 104 106 108 110 112 114 116 118]
 [120 122 124 126 128 130 132 134 136 138]
 [140 142 144 146 148 150 152 154 156 158]
 [160 162 164 166 168 170 172 174 176 178]
 [180 182 184 186 188 190 192 194 196 198]]


# Cevap 2

In [ ]:
#Parametre olarak girilen satır ve kolon sayısına göre 
#kenarları 1'lerden, içi 0'lardan oluşan dizi döndüren bir fonksiyon yazınız.

In [2]:
import numpy as np
def matris ():
    a=int(input("Matrisin 1. boyutunu giriniz : "))
    b=int(input("Matrisin 2. boyutunu giriniz : "))
    y=np.ones(a*b).reshape(a,b)
    y[1:a-1,1:b-1]=0
    
    return y
matris()

Matrisin 1. boyutunu giriniz : 5
Matrisin 2. boyutunu giriniz : 6


array([[1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1.]])